MODEL:
    PATH: 'degree_project/model/pose_estimation/body_pose_model.pth'
    LOAD_FINETUNED_WEIGHTS: False
    FINE_TUNED_WEIGHTS_PATH: 'degree_project/model/pose_estimation/model.h5'
POSE_ESTIMATION:
    VIDEO_FOLDER: /Midgard/Data/tibbe/datasets/own/
    OUTPUT_FOLDER: degree_project/output/pose_estimation
POSES:
    PATH: /Midgard/Data/tibbe/datasets/own/pose_sequences_openpose_renamed/
    SMOOTH_OUT_PATH: /Midgard/Data/tibbe/datasets/own/pose_sequences_openpose_renamed_smooth/
POST_PROCESS:
    MODE: 'from_df' # options: [from_dict, from_df]