model:
    name: scripts.FM_classification.VanillaVAE:VanillaVAE
    params:
        in_dim: 360 # 4*18*5
        latent_dim: 32
        hidden_dim: 3
dataset:
    name: data.datasetKI:KI_Dataset_VAE
    transform:
        enable: false
        name: data.augmentations:RandScale
        params:
            magnitude: 0.5 # [0, 1]
            p: 0.9 # [0, 1]
            class_agnostic: false
    mapping: {'1': 0, '4': 0, '12': 1} # {'1': 0, '4': 1, '12': 2} or {'1': 0, '4': 0, '12': 1}
    sampling: 
        enable: true
        method: oversampling # options: [oversampling, undersampling]
    params:
        data_folder: /Midgard/Data/tibbe/datasets/own/poses_smooth_np/
        annotations_path: /Midgard/Data/tibbe/datasets/own/annotations.csv
        feature_type: "kinematics"
        sample_len: 5
        stride: 1
        fps: 25
hparams:
    epochs: 200
    batch_size: 1
    validation_period: 1
    optimizer:
        name: torch.optim:Adam
        params:
            lr: 0.0025
            betas: [0.9, 0.999]
            weight_decay: 0.01
    scheduler:
        name: scripts.FM_classification.optimizer:CosineDecayWithWarmUpScheduler
        params:
            step_per_epoch: 120
            init_warmup_lr: 0.001
            warm_up_steps: 600 # 20 epochs
            max_lr: 0.0075
            min_lr: 0.001
            num_step_down: 24000 # 300 epochs
            num_step_up: 0 # None (empty is none)
            T_mul: 1
            max_lr_decay: Exp
            gamma: 0.5
            min_lr_decay: Exp
            alpha: 0.5
save_path: /local_storage/users/tibbe/models/VAE/
wandb:
    enable: false