model:
    name: scripts.FM_classification.VanillaVAE:VanillaVAE
    params:
        in_dim: 140 # 2*6*5 ####360 # 4*18*5
        hidden_dim: 32
        latent_dim: 3
        depth: 2
        beta: 0.0071 # 1/120
    params_GCN_VAE:
        in_dim: 10 # 2*5
        num_joints: 14
        hidden_dim: 4
        latent_dim: 2
        depth: 4
        beta: 0.000714 # 1/14
dataset:
    name: data.datasetKI:KI_Dataset_VAE
    transform:
        enable: true
        name: data.augmentations:RandScale
        params:
            magnitude: 0.5 # [0, 1]
            p: 0.9 # [0, 1]
            class_agnostic: false
    mapping: {'1': 0, '4': 0, '12': 1} # {'1': 0, '4': 1, '12': 2} or {'1': 0, '4': 0, '12': 1}
    sampling: 
        enable: false
        method: oversampling # options: [oversampling, undersampling]
    params:
        # data_folder: /Midgard/Data/tibbe/datasets/own/poses_smooth_np/
        data_folder: /Volumes/USB3/thesis/data/np_poses_corrected/
        # annotations_path: /Midgard/Data/tibbe/datasets/own/annotations.csv
        annotations_path: /Volumes/USB3/thesis/data/annotations.csv
        max_path: data/maxs.npy
        min_path: data/mins.npy
        feature_type: "kinematics"
        sample_len: 5
        stride: 1
        fps: 25
        diff_step: 2
hparams:
    epochs: 1000
    batch_size: 1
    orig_dim: [2, 14, 5]
    validation_period: 1
    optimizer:
        name: torch.optim:Adam
        params:
            lr: 0.0025
            betas: [0.9, 0.999]
            weight_decay: 0.01
    scheduler:
        name: scripts.FM_classification.optimizer:CosineDecayWithWarmUpScheduler
        params:
            step_per_epoch: 1
            init_warmup_lr: 0.0005
            warm_up_steps: 40 # 20 epochs
            max_lr: 0.0075
            min_lr: 0.0075
            num_step_down: 20 # 300 epochs
            num_step_up: 0  # None (empty is none)
            T_mul: 1
            max_lr_decay:
            gamma: 0.5
            min_lr_decay:
            alpha: 0.5
# save_path: /local_storage/users/tibbe/models/VAE/
save_path: /Volumes/USB3/thesis/models/VAE/
wandb:
    enable: true
plot_reconstruction:
    enable: true
    period: 100