model:
    name: model:STTransformer
    in_features: distance_mat # options: [distance_mat, kinematics(pos, vel, acc, depth)]
    load_weights:
        enable: true
        path: model/FM_classification/STTransformer.pth
    in_params:
        joint_in_channels: 2
        joint_hidden_channels: 64
        time_window: 9
        time_step: 3
        dropout: 0.4
    save_period: 50
dataset:
    name: data.dataset_KI:KIDataset
    fps: 25
    mapping: {'1': 0, '4': 1, '12': 2}
    sampling: 
        enable: true
        method: oversampling # options: [oversampling, undersampling]
    params:
        data_folder: /Midgard/Data/tibbe/datasets/own/poses_smooth_np/
        # data_folder: /Users/magnusrubentibbe/Dropbox/Magnus_Ruben_TIBBE/Uni/Master_KTH/Thesis/code/data/dataset_KI/poses_smooth_np/
        # annotations_path: /Users/magnusrubentibbe/Dropbox/Magnus_Ruben_TIBBE/Uni/Master_KTH/Thesis/code/data/dataset_KI/annotations.csv
        annotations_path: /Midgard/Data/tibbe/datasets/own/annotations.csv
hparams:
    epochs: 1
    batch_size: 1
    validation_period: 5
    criterion: 
        name: loss:CrossEntropyLoss
        params: # only used for WeightedCrossEntropyLoss
            weights: [2.61538462, 1.61904762, 0.5] # label distribution: [13, 21, 68]; calc: (total/occurence)/num_classes
    optimizer:
        name: SGD
        params:
            lr: 0.1
            weight_decay: 0.0001
    scheduler:
        name: CyclicLR
        params:
            base_lr: 0.00025
            max_lr: 0.025
            mode: triangular2
logger:
    name: wandb
    enable: true
outputs:
    path: output/FM