model:
    name: model:STTransformer
    in_features: distance_mat # options: [distance_mat, kinematics(pos, vel, acc, depth)]
    in_params:
        joint_in_channels: 2
        joint_hidden_channels: 64
        time_window: 9
        time_step: 3
dataset:
    name: data.dataset_KI:KIDataset
    fps: 25
    params:
        data_folder: /Midgard/Data/tibbe/datasets/own/pose_sequences_openpose_renamed_smooth/
        annotations_path: /Midgard/Data/tibbe/datasets/own/annotations.csv
hparams:
    epochs: 200
    batch_size: 1
    criterion: CrossEntropyLoss
    optimizer:
        name: SGD
        params:
            lr: 0.1
            weight_decay: 0.0001
    scheduler:
        name: CyclicLR
        params:
            base_lr: 0.001
            max_lr: 0.1
